/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error-container": "#93000a",
        "on-secondary-container": "#adb4ce",
        "inverse-on-surface": "#2a3043",
        "surface-container-low": "#151b2d",
        "secondary-container": "#3f465c",
        "on-tertiary-container": "#2a3a4f",
        "primary": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "on-primary-fixed": "#002113",
        "on-tertiary": "#213145",
        "glow-emerald": "rgba(16, 185, 129, 0.15)",
        "surface-container-highest": "#2e3447",
        "on-tertiary-fixed-variant": "#38485d",
        "terminal-header": "#0F172A",
        "on-primary-container": "#00422b",
        "on-error": "#690005",
        "tertiary": "#b7c8e1",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-fixed": "#0b1c30",
        "surface-bright": "#33394c",
        "surface-container": "#191f31",
        "outline-variant": "#3c4a42",
        "secondary-fixed": "#dae2fd",
        "surface-elevated": "#1E293B",
        "on-surface": "#dce1fb",
        "surface-variant": "#2e3447",
        "background": "#0c1324",
        "surface-dim": "#0c1324",
        "primary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#bec6e0",
        "on-background": "#dce1fb",
        "error": "#ffb4ab",
        "surface-container-lowest": "#070d1f",
        "inverse-primary": "#006c49",
        "tertiary-fixed": "#d3e4fe",
        "primary-container": "#10b981",
        "on-primary-fixed-variant": "#005236",
        "on-error-container": "#ffdad6",
        "surface": "#0c1324",
        "on-secondary-fixed": "#131b2e",
        "surface-container-high": "#23293c",
        "inverse-surface": "#dce1fb",
        "on-primary": "#003824",
        "surface-tint": "#4edea3",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-surface-variant": "#bbcabf",
        "tertiary-container": "#94a4bd",
        "secondary": "#bec6e0",
        "on-secondary": "#283044",
        "outline": "#86948a"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1200px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "unit": "8px",
        "section-gap": "128px"
      },
      "fontFamily": {
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "label-caps": ["JetBrains Mono"]
      },
      "fontSize": {
        "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "code-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
};
